### ISSUE TITLE
ad_conn behind_secure_proxy_p returns "", breaking if {...}

### ISSUE THREAD

**Issue by fraber** [openacs/openacs-core#4]
Hi!

https://github.com/openacs/openacs-core/blob/master/packages/acs-tcl/tcl/utilities-procs.tcl

Line 1924 in master contains a "naked" "[ad_conn behind_secure_proxy_p]".
This function returns "" (empty string) instead of "0" in some strange circumstances.

=> Please fix the IF statement to check if it returns "1" or similar.

Cheers
Frank

**Comment by Elettrotecnica** [comment]
Dear Frank,

by looking at the code, I do not understand how is it possible that ad_conn behind_secure_proxy_p returns the empty string... the code setting it clearly cannot return other than a boolean, even when outside of a connection.

Are you sure this does not have to do with some local modification? The value of this flag can be overridden using ad_conn -set or touching the global variable (but upstream we do not do it anywhere).

Would you mind giving some more details about where this is happening?

**Comment by fraber** [comment]
Hi!

I'm running OpenACS 5.9.1 on NaviServer 4.99.8 behind NGINX, but I believe this message came when connecting directly to port 8000.

It can happen if an empty string is returned by: 

`[ns_set iget [ns_conn headers] X-SSL-Request]`

That's in line 1620 at https://github.com/openacs/openacs-core/blob/master/packages/acs-tcl/tcl/request-processor-procs.tcl
That code is part of ad_conn. That does seem possible somehow, doesn't it?

In the past we had a similar issue with boolean functions returning "" and therefore breaking IF statements, but I can't find where it was. Just as a comment to be aware, as this seem to be a not-so-uncommon error.

Cheers
Frank

**Comment by gustafn** [comment]
When going back in history, i see, that this issue was resolved in 2017.

https://github.com/openacs/openacs-core/commit/05c58b86a65e39091565891128ddc76622928014
