### ISSUE TITLE
sql injection potential

### ISSUE THREAD

**Issue by miora-sora** [openacs/openacs-core#5]
these is potential to sql injection in user id  so if anyone use sql command and execute it as user id 
/packages/acs-admin/lib/become.tcl
line:17
if {![db_0or1row password {select password from users where user_id = :user_id}]} {
    ad_return_error "Couldn't find user $user_id" "Couldn't find user $user_id."
    return
}

**Comment by gustafn** [comment]
What makes you believe this? :user_id is a bind variable that automatically performs appropriate quoting.

**Comment by miora-sora** [comment]
oh ok

**Comment by gustafn** [comment]
ok, but thanks for notifying us about suspicious code. This script can be improved, anyway.
